### ISSUE TITLE
First Card Doesn't Dismiss, Spacing.

### ISSUE THREAD

**Issue by nicknagi** [dexafree/MaterialList#104]
I can't seem to get the first card to dismiss in my Material Listview. All other cards except the first one work just fine. I saw this problem in other Issues too but I just can't seem to get it working.

Also, how do I increase the spacing between cards ??

**Comment by FHellmann** [comment]
The issue with removing the first card and increasing the space between cards will be fixed with the PR #98.

**Comment by nicknagi** [comment]
When will you be releasing the new version of the library ?

**Comment by FHellmann** [comment]
I can't release the new version or merge my PR. This is something, that only @dexafree can do.

**Comment by dexafree** [comment]
I'm sorry, I've been totally out of time this latest month (I started my classes and had a pretty rough year start).

I will merge @FHellmann 's PR this week, and will update the docs accordingly.

**Comment by nicknagi** [comment]
Thanks for the info guys... Ya I understand your situation @dexafree .
