### ISSUE TITLE
is the new stuff ever gonna be released?

### ISSUE THREAD

**Issue by sirvon** [dexafree/MaterialList#105]
the new changes have been pending for a while now....
is this library gone to the wayside?

when will the dramatic change in the pending PRs be released?

thanks

**Comment by dexafree** [comment]
I was just merging it.

Unfortunately, I started my classes a month and a half ago, and I have very little time.

Also, if you need something in a PR right now, you can just clone the PR and import it as a module in your project.

I'm going to upload the jar to maven central and try to rewrite the wiki between tomorrow and Saturday.

**Comment by sirvon** [comment]
thank you @dexafree i really appreciate the quick response and your development efforts.

truly thanks for that update!

and best of luck with your classes!!

**Comment by dexafree** [comment]
Thanks :)
