### ISSUE TITLE
Second card is not dismissable

### ISSUE THREAD

**Issue by stormtheh4ck3r** [dexafree/MaterialList#112]
After dismissing the first card the second card is not getting dismissed

**Comment by FHellmann** [comment]
Have you mark the second card as dismissible?
With...
```java
card.setDismissible(true);
```
...or...
```java
Card card = new Card.Builder(this)
   .setDismissible()
   // configure
   .build();
```

**Comment by stormtheh4ck3r** [comment]
i was talking about ypour app from the playstore

**Comment by dexafree** [comment]
As said in the Readme, the Play Store version might not be the last one available

**Comment by stormtheh4ck3r** [comment]
Oh sorry, i didn't read that.

**Comment by stormtheh4ck3r** [comment]
Its actually from your app from play store that I was talking about
