### ISSUE TITLE
Unable to sync with Gradle: compile 'com.github.dexafree:MaterialList:v3.0.1'

### ISSUE THREAD

**Issue by linkindrew** [dexafree/MaterialList#114]
i'm unable to get this lib. via gradle sync. i've also tried snapshot : compile 'com.github.dexafree:MaterialList:-SNAPSHOT'  , still no success. please respond.

![screen shot 2015-12-30 at 4 30 23 pm](https://cloud.githubusercontent.com/assets/13833204/12050117/55a0ecd2-aebe-11e5-9a43-0c6799faf5fb.png)
![screen shot 2015-12-30 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/13833204/12050118/5601bbc0-aebe-11e5-8434-3443fd81e8af.png)

**Comment by dexafree** [comment]
Because you should use 

```groovy
compile 'com.github.dexafree:materiallist:3.1.2'
```
