### ISSUE TITLE
with Provider

### ISSUE THREAD

**Issue by Sankeet** [dexafree/MaterialList#116]
.withProvider(BasicImageButtonsCardProvider.class)

having error with this line "BasicImageButtonsCardProvider"

**Comment by FHellmann** [comment]
This has been changed in one of the last updates. See the [example](https://github.com/dexafree/MaterialList/blob/master/app/src/main/java/com/dexafree/materiallistviewexample/MainActivity.java#L105).

**Comment by Sankeet** [comment]
Thanks a lot..!! @FHellmann
