### ISSUE TITLE
Add check buttons on BasicListCard in V3

### ISSUE THREAD

**Issue by fedmeloni** [dexafree/MaterialList#122]
In V2 there is an example on how to implement check buttons on List entries, but it is not shown in V3. How can we do that?

**Comment by FHellmann** [comment]
You can define this in your own [ListAdapter](https://github.com/dexafree/MaterialList/blob/master/app/src/main/java/com/dexafree/materiallistviewexample/MainActivity.java#L249).

**Comment by fedmeloni** [comment]
Is there any example of how to implement it?

**Comment by FHellmann** [comment]
There are a [lot of examples](https://www.google.co.uk/search?q=android+listadapter+checkbox&oq=android+listadapter+checkbox&aqs=chrome..69i57.7127j0j1&sourceid=chrome&es_sm=93&ie=UTF-8#q=android+listview+checkbox) to find with google.
