### ISSUE TITLE
setDismissable only after action

### ISSUE THREAD

**Issue by gaiabeatrice** [dexafree/MaterialList#123]
Hi, how is it possible to set the card dismissable only after button pressing (disabling swipe) or adding an action on swipe action?

**Comment by FHellmann** [comment]
You can use the [card.setDismissible(boolean)](https://github.com/dexafree/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/card/Card.java#L64) method to set your card dismissable after a button was pressed.
To get noticed when a card was swiped out you can use the [materialList.setOnDismissCallback(...)](https://github.com/dexafree/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/view/MaterialListView.java#L161).
