### ISSUE TITLE
BUG strange behavior on "com.android.support:design:23.2.1"

### ISSUE THREAD

**Issue by fedmeloni** [dexafree/MaterialList#131]
Using com.android.support:design:23.2.1 instead of com.android.support:design:23.1.1 the carda layout looks strange, there is a lot of space between cards.

**Comment by Dunkin53000** [comment]
Same issue here

**Comment by Dunkin53000** [comment]
[FIX] In the cards layout you have to set height of the layout to wrap_content

**Comment by mlimb** [comment]
@Dunkin53000 this fixed it for me. Thanks!
