### ISSUE TITLE
 Failed to resolve: com.github.dexafree:materiallist:3.2.2

### ISSUE THREAD

**Issue by rtugeek** [dexafree/MaterialList#146]
Failed to resolve: com.github.dexafree:materiallist:3.2.2
I guess the correct version is 3.2.1 or you have not uploaded 3.2.2 to maven yet.

![2016-07-10 21-20-42](https://cloud.githubusercontent.com/assets/6168238/16713800/0d3f7ef8-46e5-11e6-99cb-9d6e3b7ab024.png)

**Comment by ameerhamza6733** [comment]
Unzip the github project to a folder. Open Android Studio. Go to File->new->Import Project. Then choose the specific project you want to import and then click Next->Finish. It will build the Gradle automatically and'll be ready for you to use.
