### ISSUE TITLE
Option to increase space between Cards without creating custom card

### ISSUE THREAD

**Issue by stripathi669** [dexafree/MaterialList#18]
I was wondering how could one tinker with few properties of the cards, such as margin and padding, depth etc. without having to create custom card.

I tried to change divided length for Material list view but it didn't work.

In addition to this, it would be wonderful if a Progress bar indicator option could be given for each card.

Thanks

**Comment by dominic69** [comment]
@stripathi669 were you able to do something about this?

**Comment by nsbrno** [comment]
I'm having the same problem. Did you get any solution?
