### ISSUE TITLE
Multiple dex  files for libcoreanimation

### ISSUE THREAD

**Issue by mshukla19** [dexafree/MaterialList#20]
Hi, I'm facing an issue.. My gradle build is failing because of multiple dex files for libcoreanimation. I checked the iml file and it is showing libcoreanimation 3.1.0 is imported by both your project and sticky list headers.. I'm defining your project as a dependency  in my gradle file. Please fix it or provide a way to quick fix  I'm a bit short on time.

**Comment by mshukla19** [comment]
When I try to import the project as a module.. It says gradle build failed because maven_push is missing.

**Comment by dexafree** [comment]
Try commenting the last line on build.gradle



—

**Comment by mshukla19** [comment]
Hi, importing the project and then commenting the last line worked for me.. But still those who want to declare it as a dependency in build. Gradle might face the multiple dex issue. So in spare time please look into that also. 
Thank you.
