### ISSUE TITLE
multifile defined

### ISSUE THREAD

**Issue by jiqimaogou** [dexafree/MaterialList#26]
17:14:53.374 [ERROR] [org.gradle.BuildExceptionReporter]
17:14:53.374 [ERROR] [org.gradle.BuildExceptionReporter]   	UNEXPECTED TOP-LEVEL EXCEPTION:
17:14:53.374 [ERROR] [org.gradle.BuildExceptionReporter]   	com.android.dex.DexException: Multiple dex files define Lcom/nhaarman/listviewanimations/util/Swappable;
17:14:53.374 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.command.dexer.Main.run(Main.java:246)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.command.dexer.Main.main(Main.java:215)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]   		at com.android.dx.command.Main.main(Main.java:106)
17:14:53.375 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by FHellmann** [comment]
See #21

**Comment by dexafree** [comment]
Definitely fixed in version 2.1.0
