### ISSUE TITLE
version 2.0.1 error

### ISSUE THREAD

**Issue by csechuan** [dexafree/MaterialList#28]
I got this error with this version. I cant compile. 

Note: there were 19 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning:com.dexafree.materialList.model.BasicButtonsCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BasicImageButtonsCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BigImageButtonsCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BigImageCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.SmallImageCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.WelcomeCard: can't find superclass or interface com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BasicButtonsCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BasicImageButtonsCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BigImageButtonsCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.BigImageCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.CardList: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.GridItemView: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.SmallImageCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:com.dexafree.materialList.model.WelcomeCard: can't find referenced class com.dexafree.materialList.model.Card
Warning:there were 21 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
:app:proguardDebug FAILED
Error:Execution failed for task ':app:proguardDebug'.
> java.io.IOException: Please correct the above warnings first.

**Comment by FHellmann** [comment]
Have you tried to clean your project up and rebuild it?

**Comment by csechuan** [comment]
yeah it happens after cleaned.

**Comment by FHellmann** [comment]
The Classes which can't be found moved from "com.dexafree.materialList.model" to "com.dexafree.materialList.cards.model".

**Comment by meanmee** [comment]
when i add compile 'com.github.dexafree:materiallist:2.0.3' to my  build.gradle,there are some problem i can't sovle ,please help me,thank u very much
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.dexafree:materialList:2.0.3.
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3
      > inconsistent module metadata found. Descriptor: com.github.dexafree:materiallist:2.0.3 Errors: bad module name: expected='materialList' found='materiallist'
   > Could not find com.android.support:cardview-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3
   > Could not find com.android.support:appcompat-v7:21.0.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3

**Comment by dexafree** [comment]
@meanmee see https://github.com/dexafree/MaterialList/issues/36

Also, it would be great if @csechuan told if the issue is solved :)

**Comment by meanmee** [comment]
sorry ,i'm to github and Android Studio,
when i add compile 'com.github.dexafree:materiallist:2.0.1'  to build.gradle
there are some problems like this:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.0/appcompat-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.0/appcompat-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1
   > Could not find com.android.support:cardview-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1
   > Could not find any version that matches com.android.support:support-v4:19.1.+.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
         https://jcenter.bintray.com/com/android/support/support-v4/
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1 > com.etsy.android.grid:library:1.0.5
