### ISSUE TITLE
Sample Cards as Gradle Import

### ISSUE THREAD

**Issue by FHellmann** [dexafree/MaterialList#36]
Shouldn't the sample cards also be able to import via gradle into the own project?

```java
    import 'com.github.dexafree:materiallist-cards:x.x.x'
```

**Comment by dexafree** [comment]
Yes, I'm working on it, the refactor about the project structure made it crash.

I will try to solve it today.

Since then, please use 2.0.1

**Comment by dexafree** [comment]
I'm having serious trouble in multiple dex definitions (com.nhaarman.listviewanimations).

I'm considering joining again both modules into one single module

**Comment by meanmee** [comment]
thanks,come on.

**Comment by meanmee** [comment]
sorry to bother u again,i'm new to github and Android Studio,
when i add compole 'com.github.dexafree:materiallist:2.0.1',there are some problems like these:
     Error:(28, 0) Gradle DSL method not found: 'compole()'
Possible causes:<ul><li>The project 'Smart Home+' may be using a version of Gradle that does not contain the method.
<a href="openGradleSettings">Gradle settings</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by meanmee** [comment]
sorry ,i have changed "compole" to compile",but there are also some problems:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.0/appcompat-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.0/appcompat-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1
   > Could not find com.android.support:cardview-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1
   > Could not find any version that matches com.android.support:support-v4:19.1.+.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
         https://jcenter.bintray.com/com/android/support/support-v4/
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.1 > com.etsy.android.grid:library:1.0.5
