### ISSUE TITLE
hello ,i'm from China，and my English is poor,i will try my best to let you know my problem,thank u.

### ISSUE THREAD

**Issue by meanmee** [dexafree/MaterialList#38]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.dexafree:materialList:2.0.3.
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3
      > inconsistent module metadata found. Descriptor: com.github.dexafree:materiallist:2.0.3 Errors: bad module name: expected='materialList' found='materiallist'
   > Could not find com.android.support:cardview-v7:21.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/21.0.0/cardview-v7-21.0.0.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3
   > Could not find com.android.support:appcompat-v7:21.0.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.jar
     Required by:
         SmartHome+:app:unspecified > com.github.dexafree:materiallist:2.0.3

**Comment by dexafree** [comment]
See https://github.com/dexafree/MaterialList/issues/36
