### ISSUE TITLE
Trying to use this but...

### ISSUE THREAD

**Issue by drabelo** [dexafree/MaterialList#39]
Whenever I try to initiate a card it says not valid. Even the sample one's in your wiki. I am using gradle dependency with version 2.0.7. I saw earlier in your post that you told someone to use 2.0.1, since it could fix the card issue. It still didn't for me. Are we supposed to have 2 different gradle dependencies for cards and the actual library?

Would appreciate help!

**Comment by dexafree** [comment]
Yes, 2.0.1 - 2.0.7 is broken.

I'm trying to fix it, but it looks like I will have to join again the two modules in one, because I'm having dex issues.

I hope to have it solved today
