### ISSUE TITLE
MateriaList with Picasso

### ISSUE THREAD

**Issue by RicardoRB** [dexafree/MaterialList#41]
Hi! I am using this awesome library and I am trying to mix with picasso, but I need a ImageView to do this, and I do not know how do it, I tried to inflate the layout but it does not work. So I wonder if could you tell me how can I mix them, maybe if there was a "getImageView()" or something could it be more easy.

Thanks you, so much!

**Comment by dexafree** [comment]
If you need an ImageView reference, you can add the metioned `getImageView()` to the BaseTextCardItemView, so it will be available for all its child classes (I have in mind creating a class inheritance diagram) 

https://github.com/dexafree/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/cards/internal/BaseTextCardItemView.java

The code would be as simple as

```java
public ImageView getImageView(){
    ImageView imageView = (ImageView)findViewById(R.id.imageView);
   return imageView;
}
```

Of course you should check nulls.

All ImageView declarations in the layouts are declared with the id `R.id.imageView`.

If you get it to work, feel free to make a Pull Request :+1:

**Comment by RicardoRB** [comment]
Thank you, let me test it and I will do a pull request if everything run right :)

**Comment by RicardoRB** [comment]
When I tried to import as a module in android studio, it throw me this error:

Error:No such property: POM_DESCRIPTION for class: org.gradle.api.publication.maven.internal.CustomModelBuilder

Do you know how can I fix it?

**Comment by dexafree** [comment]
How did you import it? By cloning and adding as a dependency?

**Comment by RicardoRB** [comment]
I downloaded it from github, imported as module in android studio option and the IDE try to compile with gradle but it throw me that error.

**Comment by dexafree** [comment]
Try commenting the last line on the module's build.gradle, the `apply from`

**Comment by RicardoRB** [comment]
That works! But I can not take the ImageView yet, I tried this:

// Image
        ImageView imageView = (ImageView) findViewById(R.id.imageView);
        if (imageView != null) {
            imageView.setImageDrawable(card.getDrawable());
            card.setImageView(imageView);
        }

It does no works, it return me a null. If I tried putting "getImageView()" method in BaseTextCardItemView, I do not know how can I access it to take it.

**Comment by dexafree** [comment]
Where did you put that code?
You are not meant to interact to the Card View from the Activity. If you want to define a new behaviour you should define a new Card, with its own ItemView element (I think you are pretending to do it that way)

**Comment by RicardoRB** [comment]
I put the code in BaseTextCardItemView. Must I define a new Card to just take the ImageView? All I want is the ImageView from BigImageCard, there is no way to modify it to return me him object?

**Comment by RicardoRB** [comment]
I did it!

I put a pull request, tell me anything about it if you see anything wrong. :smile:
