### ISSUE TITLE
Help with the list..

### ISSUE THREAD

**Issue by MelodyAustin** [dexafree/MaterialList#46]
How can I set onscrolllistner and how to set onitemclicklistner for the entire card? Please help. I would like to hide the toolbar with the help of onscroll listener and I want an activity to be opened by clicking anywhere on the card. 

How to set onscrolllistener and onitemclicklistner please help..

**Comment by dexafree** [comment]
I'm working on being able to add a custom onScrollListener without interfering with the Swipe2Dismiss, and also setting an onItemClickListener.

I think I will finish it this week

**Comment by stripathi669** [comment]
@MelodyAustin : For onitem click listener, you can download dexafree's samplecards, create clicklisternet in <Cardname>.java, and activate it using <Cardname>view.java 

Read the card code for more details.
