### ISSUE TITLE
Sensitivity Issue of Swipe to Dismiss

### ISSUE THREAD

**Issue by stripathi669** [dexafree/MaterialList#47]
I am facing sensitivity issues regarding swipe to dismiss feature. Often while scrolling, I accidentally dismiss a card just by touching the card. The dismiss feature appears to be very sensitive to touch.

Is there a way to reduce sensitivity of of swipe to dismiss in Material List view ?

**Comment by stripathi669** [comment]
@dexafree : Do you have any advice for me ?

**Comment by dexafree** [comment]
Sorry, I'm not an expert in Custom Views on Android.

I tried tweaking a little bit the values at the `onTouch` method in https://github.com/dexafree/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/controller/SwipeDismissRecyclerViewTouchListener.java , both on `ACTION_UP` and `ACTION_MOVE`, but it ended up not feeling ok (the swipe needed to be done until the end of the screen, and sometimes it messed up with the scroll sometimes).

If you try to edit it and get some nice values, feel free to PR, as it's something that maybe other developers would also appreciate.

Sorry for not being able to help

**Comment by stripathi669** [comment]
I have found a very bizarre solution to this.

I have set On click listeners to few components of the card (say title text, description). That way, the net swipable area (which you drag to dismiss a card) has reduced.

It may sound stupid, but this works and now I don't accidentally don't swipe away a card.
