### ISSUE TITLE
OnItemClickListeners implementation

### ISSUE THREAD

**Issue by konigsoft** [dexafree/MaterialList#48]
Hi dexafree i'm using your nice library and i am missing the onitemclick listener.
Is there a way to implement it ou it is plan for the next release ?

looking forward to hearing from you.

regards,

**Comment by dexafree** [comment]
It's quite simple to implement, I have already included it in the version I'm working, but I'm facing some issues while trying to develop a common View that works both on Portrait and Landscape

**Comment by phoenixstudio** [comment]
Hi, I'm looking for this issue also.
Do you mind sharing the idea on how to implement it?
I've created custom class that extends the simplecard and carditemview for that class.
thanks.

**Comment by dexafree** [comment]
I'm working on it, since now it's based on RecyclerView and it does not provide an OnItemClickListener by default

**Comment by dexafree** [comment]
You can check the status at
https://github.com/dexafree/MaterialList/tree/onItemClickDevelopment

The sample app shows the implementation, feel free to check and test

**Comment by konigsoft** [comment]
great news
thank you very much

**Comment by dexafree** [comment]
With last version it should be working

**Comment by konigsoft** [comment]
thank you very much
will give a try
