### ISSUE TITLE
Implementing a custom card

### ISSUE THREAD

**Issue by ricpacca** [dexafree/MaterialList#53]
Hello,
I'm having some troubles in implementing a custom card in my project.
I tried to follow your guide here:
https://github.com/dexafree/MaterialList/wiki/Create-your-own-Cards

But when I define the ItemView class like this:
public class CustomCardItemView extends GridItemView<CustomCard>

AndroidStudio tells me that it cannot resolve the symbol 'GridItemView'.
It simply doesn't recognize/find it.

How can I solve this problem?
Thanks very much in advance

**Comment by FHellmann** [comment]
You have to use the CardItemView. I think this class was renamed from GridItemView to CardItemView.

**Comment by dexafree** [comment]
Yes, the docs need some update. Will try to find some time to update the section :)

**Comment by sebastialonso** [comment]
@ricpacca were you able to make it work?
If so, would you mind dumb the process down a little bit?

**Comment by ricpacca** [comment]
Hi @sebastialonso, sorry but I don't remember how I made it work at that time, but recently I decided to switch to using the recyclerview/cardview from google, which works fine and has a good documentation on the internet, so I suggest you to try that one ;)
