### ISSUE TITLE
Failed to find: com.github.dexafree:materiallist:2.3.2

### ISSUE THREAD

**Issue by zonex5** [dexafree/MaterialList#56]
I have this message when try to compile project
   Error:Failed to find: com.github.dexafree:materiallist:2.3.2

it works only for version 2.0.1

**Comment by dexafree** [comment]
Weird issue :anguished: 

It compiles perfectly, and also it can be found at Maven Central

http://search.maven.org/#artifactdetails|com.github.dexafree|materiallist|2.3.2|
