### ISSUE TITLE
how to import it in eclipse?

### ISSUE THREAD

**Issue by anmolnimbalkar** [dexafree/MaterialList#58]
I have created a new library project for materialLib
1) copied all files in that project
2) added cardview, recyclerview library to that
3) added its jar to import/export
4) added the jars: otto, nineoldandroids, listviewanimation_lib to bulld path and in import/export check
5) clean and build

But when i am importing and running it in my project it shows
error inflating class android.support.v7.widget.cardview
and same for recyclerview

anybody please tell me how to solve this issue?

**Comment by sturmen** [comment]
Hi! Unfortunately, [Eclipse is no longer supported by Google](http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html) and all Android developers are encouraged to switch to Android Studio. Once you have Android Studio up and running, adding MaterialList is as easy as adding a line to your Gradle file. Hope this helps!
