### ISSUE TITLE
The  function of dismiss Card doesn't work.

### ISSUE THREAD

**Issue by superlittlebinbin** [dexafree/MaterialList#59]
mListView.setOnDismissCallback(new OnDismissCallback())

This function can not work.

**Comment by stasusov** [comment]
Same. I thought it is because my Fragment-based design, or self-created cards, or old version of library. Tried default cards and new version of library, no results. Also tried to write to log and make Toasts, but had seen only default Log message about card dismiss.

**Comment by dexafree** [comment]
Should be fixed with https://github.com/dexafree/MaterialList/commit/61099d9e84b1056c117bc0d047cac677541f6567

**Comment by stasusov** [comment]
Thanks, works now
