### ISSUE TITLE
BasicListCard

### ISSUE THREAD

**Issue by kenny0202** [dexafree/MaterialList#63]
Very good work on the library. I just have some issues using the BasicListCard.
I have added the dependencies and the code for the layout. In the activity itself I have created a BasicListCard, but it seems that methods addItem and addAllItems does not exist.

**Comment by FHellmann** [comment]
Yes, these methods does not exists any more. I removed them to replace them with a ListAdapter. This is a more flexible way to handle the layout of the ListItems by yourslef.

**Comment by kenny0202** [comment]
Ok Thanks for letting me know.
