### ISSUE TITLE
Empty layouts

### ISSUE THREAD

**Issue by twinone** [dexafree/MaterialList#68]
For example in ButtonsCard, when setting left or right button text to "" or null, an empty button is created. This should not happen.

Also when both buttons are null or "" the whole button "holder" should dissapear, without leaving a big padding on the bottom.

I'll send a pull request if I have time to fix it.

**Comment by dexafree** [comment]
If you want no buttons at all, why use a Card that has buttons?
Most have their equivalent with/without buttons.
