### ISSUE TITLE
Method setRightButtonTextColorRes seems to be not working

### ISSUE THREAD

**Issue by tral** [dexafree/MaterialList#69]
Hello! Try to add in your demo app this code:

`((BasicButtonsCard) card).setRightButtonTextColorRes(R.color.divider_white);`

(It is in `MainActivity.getRandomCard` method, in  `case 3: ...`)

The color of the right button never changes. Bug?

**Comment by tral** [comment]
The same thing with setRightButtonTextColor method

**Comment by dexafree** [comment]
You are right.

Fixed in: https://github.com/dexafree/MaterialList/commit/99af8c4595691a6d306b2cdc12006b95c78c1a0f

Will be available in 2.4.3 (which should be available in Maven Central in a couple of hours)

**Comment by tral** [comment]
Thanks a lot!
