### ISSUE TITLE
Update to 2.4.0 on jitpack

### ISSUE THREAD

**Issue by jlwatkins** [dexafree/MaterialList#70]
Can you please upload 2.4.0+ to jitpack.io so that I can use it using the basic dependencies?

**Comment by dexafree** [comment]
As I can see, then only think I have to do in order for it to be available in jitpack.io is to make a Release, right?

Never heard about that system before

**Comment by jlwatkins** [comment]
I put an invalid number in my retrieval. The jitpack package page said 4.2.0 so I was using that. I apologize. New to this jitpack stuff. I just had to change it to a specific existing version

**Comment by dexafree** [comment]
I created a release of the v2.4.3, so now you can use the last version ;)

BTW, why do you use the jitpack version instead of the maven central one?
