### ISSUE TITLE
no card.dismiss() method

### ISSUE THREAD

**Issue by sturmen** [dexafree/MaterialList#75]
I'm trying to use the Welcome Card, but it seems to be only swipe-to-dimiss.
```
WelcomeCard welcomeCard = new WelcomeCard(context);
welcomeCard.setDismissible(true);
welcomeCard.dismiss();
```
Android Studio refuses the `.dismiss()` method and it will not compile, either. The button to dismiss on the Welcome Card also does not work, I assume because it made a call to `.dismiss()`

**Comment by dexafree** [comment]
The API changed a little bit.

Now the cards should be dismissed via the MaterialList object:

https://github.com/dexafree/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/view/MaterialListView.java#L116


Here you can see the call at the sample project: 
https://github.com/dexafree/MaterialList/blob/master/app/src/main/java/com/dexafree/materiallistviewexample/MainActivity.java#L135

**Comment by sturmen** [comment]
works like a charm! Thanks.
