### ISSUE TITLE
classCastException android.graphics.drawable.colordrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow

### ISSUE THREAD

**Issue by ourstartup** [dexafree/MaterialList#79]
app crashes at cardView.setBackgroundColor(card.getBackgroundColor()); 
i used setCardBackgroundColor which solved the crashing issue.
original code is at BaseCardItemView.java line:46

**Comment by dexafree** [comment]
Will be fixed in next version, I found why it was happening.
