### ISSUE TITLE
MaterialListView is not compatible with ListView

### ISSUE THREAD

**Issue by andrusiak** [dexafree/MaterialList#80]
<b>Is there any easy way to make MaterialListView work with ListView?</b>

As far as I see if I want to work with the Cards and MaterialListView, I have to transform my BaseAdapter to RecyclerAdapter (implement new methods, change a little the old ViewHolder). Or am I wrong? 
@dexafree

**Comment by dexafree** [comment]
The idea is that you don't have to write any adapter nor RecyclerView.

You only need to add a MaterialListView, retrieve it from your code, and add Cards, you don't have to write any internal code about how will it be displayed
