### ISSUE TITLE
can you remove ic_launcher icon in the resource file?

### ISSUE THREAD

**Issue by jiqimaogou** [dexafree/MaterialList#81]

**Comment by dexafree** [comment]
It is used as a sample image at some cards, not used by any means as it was originally created (as a launcher icon).
Does it cause any collision?

**Comment by philipjmurphy** [comment]
With a default sample project it also includes this icon so there is a collision.

...\app\build\intermediates\res\debug\drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.
...\app\build\intermediates\res\debug\drawable-hdpi\ic_launcher.png: Original is here. The version qualifier may be implied.

**Comment by SteveEdson** [comment]
+1, its preventing me from using gradle 1.2.3. Moving back to v1.1.3 works ok.

**Comment by dexafree** [comment]
Fixed: https://github.com/dexafree/MaterialList/commit/946b34aa4edcc2d4ff88eefbeb0c4b1beb9f519e

Changed name to sample_android.

v2.4.5 should be up in a couple hours (sorry I do not have much time lately)

**Comment by SteveEdson** [comment]
Thanks :+1:

**Comment by philipjmurphy** [comment]
Thanks :+1: - no worries re time - it's great that you've created such an awesome library.
