### ISSUE TITLE
Update RecyclerView library version

### ISSUE THREAD

**Issue by InfinityApps** [dexafree/MaterialList#83]
Thanks for creating this wonderful library. I am recently getting into the new Design Support Library and its CoordinatorLayout. It seems the latest RecyclerView library is required to enable interaction with the CoordinatorLayout. Please fix the dependency version. Great thanks!

**Comment by dexafree** [comment]
Fixed: https://github.com/dexafree/MaterialList/commit/946b34aa4edcc2d4ff88eefbeb0c4b1beb9f519e

I updated the RecyclerView library, the support-v7 and the CardView one.

v2.4.5 should be up in a couple hours (sorry I do not have much time lately)
