### ISSUE TITLE
Activity fails to load when not setting button text

### ISSUE THREAD

**Issue by PDDStudio** [dexafree/MaterialList#84]
Tested this with BasicButtonsCard, setting only the Text for the left Button!
If you create a BasicButtonsCard and setting  only one Button's text the program may compile without any errors, but the Activity will fail to start.

Reason:

This is caused by 
> com.dexafree.materialList.cards.internal.BaseButtonsCardItemView.java

in the ```
.build ()
``` method when it comes to
```java
     leftText.setText(card.getLeftButtonText().toUpperCase());
``` 
and
```java
    rightText.setText(card.getRightButtonText().toUpperCase());
```

It'll throw a NullPointerException and the activity crashes.

(This is my first BugReport so in case I missed something please tell me)

**Comment by fatihturgut** [comment]
Hi,
Nice bug report ! @PDDStudio :+1: 
I have the same problem, i don't want to use buttons. When i don't use buttons, i get an error.
@dexafree : Could you fix it? or could you give an alternative suggestion?
Thank you.

**Comment by dexafree** [comment]
I will set an empty text if there's no leftButtonText/rightButtonText defined :+1:

**Comment by dexafree** [comment]
Solved at https://github.com/dexafree/MaterialList/commit/0c2c4f6eacf0daff710765afc129185660ce2f01

**Comment by fatihturgut** [comment]
It worked, nice job! @dexafree :+1:

**Comment by PDDStudio** [comment]
Thank you @fatihturgut ! :smile: And thanks for the fix @dexafree  :+1:
