### ISSUE TITLE
java.util.zip.ZipException duplicate entry

### ISSUE THREAD

**Issue by dhruvilbadani** [dexafree/MaterialList#89]
This is my build.gradle file:

------------------------------------------------------------------------------------------------------------------------------

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0 rc2"

    defaultConfig {
        applicationId "com.sampleapp.app1"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile files('libs/picasso-2.5.2.jar')
    compile 'com.github.dexafree:materiallist:2.4.5'
}

------------------------------------------------------------------------------------------------------------------------------

This leads to the following error when I try to run the application:

Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/squareup/picasso/Action$RequestWeakReference.class
:app:packageAllDebugClassesForMultiDex FAILED
:app:collectDebugMultiDexComponents

How can I solve this?

**Comment by FHellmann** [comment]
You already include picasso with materiallist. This means, you don't have to include it again, this leads to an duplicate entry.

**Comment by dhruvilbadani** [comment]
Yes, but even if I remove the line:

compile files('libs/picasso-2.5.2.jar')

I get the same error. Any idea why?

**Comment by dexafree** [comment]
You have included the Picasso library in your libs/ folder, and MaterialList also includes it.

So, it would not be necessary for you to include it again, you can remove it from your libs/ folder.

**Comment by dhruvilbadani** [comment]
Okay, so I deleted the picasso-2.5.2.jar file from the libs folder and removed the line 'compile files('libs/picasso-2.5.2.jar')' from my build.gradle. Now the exception is gone. Thank you for the quick help, @FHellmann  and @dexafree.

**Comment by dexafree** [comment]
Glad to help :+1: 

Thanks again @FHellmann !
