### ISSUE TITLE
SetText to custom view inside custom layout

### ISSUE THREAD

**Issue by lnikell** [dexafree/MaterialList#94]
Hello. I created custom RippleBigImageCard extends by  BigImageButtonsCard and also I redefined getLayout() which return my custom layout.
I want to add custom view with date to my layout and setText to this view after creating instance of RippleBgImageCard, but I don't understand how can  I do that.

**Comment by dexafree** [comment]
You need to create your `RippleBgImageCardItemView`, which should extend `BaseButtonsCardItemView<RippleBgImageCard>`.

In this new class, provide the 3 default constructors.

Then, override the `void build(final RippleBgImageCard card)` method, and ensure to first call the super.build(card) method.

After that, you can edit the view as you want (setText...)

**Comment by lnikell** [comment]
Thank you very much!
