### ISSUE TITLE
Bugs in MaterialListAdapter

### ISSUE THREAD

**Issue by FHellmann** [dexafree/MaterialList#96]
There is a bug, that the MaterialList can not be cleared.

I think the issue can resolved by removing the incremtation of index.
```java
    public void clear() {
        while(!mCardList.isEmpty()) {
            remove(mCardList.get(0), false);
        }
    }
```

Also is a bug in the MaterialListAdapter.getCard(int). The minimum position can be 0 but if the method is called with 0 as parameter, it returns null. There for need to ask position is >= 0 not only > 0.
```java
    public Card getCard(int position) {
        if(position >= 0 && position < mCardList.size()) {
            return mCardList.get(position);
        }
        return null;
    }
```

**Comment by dexafree** [comment]
It does not work.

The while loop sticks forever, and it only decrements the size in 1 unit.

The current implementation is unable to remove the BigImageCards, and only removes the visible cards.

**Comment by FHellmann** [comment]
Oh yes... If cards are added which can not be dismissed, then the while is an endless loop.

Maybe this works well
```java
    public void clear() {
        for (int index = 0; index < mCardList.size()) {
            if(!mCardList.get(index).isDismissible()) {
                index++;
            }
            remove(mCardList.get(index), false);
        }
    }
```

**Comment by dexafree** [comment]
The `clear`method behaviour should be to delete all the cards, or only the dismissable ones?

**Comment by FHellmann** [comment]
This is a good question. Maybe someone only want's to delete the Cards which are dismissable and others want to delete all Cards. So maybe we should create 2 different methods. One method (e.g. clearAll()) to remove every Card and another one (e.g. clear()) to remove only dismissable Cards.

**Comment by dexafree** [comment]
I've already implemented the `clear` and the `clearAll` methods, but they only seem to delete the visible cards.

```java
public void remove(@NonNull final Card card, boolean animate) {
        if (card.isDismissible()) {
            forceRemove(card, animate);
        }
    }

    public void forceRemove(@NonNull final Card card, boolean animate) {
        card.getConfig().deleteObserver(this);
        if (animate) {
            mAnimation.animate(getPosition(card));
        } else {
            mCardList.remove(card);
            notifyDataSetChanged();
        }
    }

    public void clearAll() {
        for (int index = 0; index < mCardList.size(); index++) {
            forceRemove(mCardList.get(index), false);
        }
    }

    public void clear() {
        for (int index = 0; index < mCardList.size(); index++) {
            remove(mCardList.get(index), false);
        }
    }
```

**Comment by FHellmann** [comment]
I think the problem is when removing items from a list with a for-loop.
```java
for(int index = 0; index < mCardList.size(); index++) { ... }
```
The first item (index = 0) will be removed. After that, the items will update the index. For example [name(position)]:

```
List: Item1(0), Item2(1), Item3(2), Item4(3), Item5(4), Item6(5)

**remove item at index 0**
**increment index=1**

List: Item2(0), Item3(1), Item4(2), Item5(3), Item6(4)

**remove item at index 1**
**increment index=2**

List: Item2(0), Item4(1), Item5(2), Item6(3)

**remove item at index 2**
**increment index=3**

List: Item2(0), Item4(1), Item6(2)

**Finished!**
```

This example shows that the index should only be increment if a card is not dismissable (if not forceRemove is called).

Try this:
```java
    public void remove(@NonNull final Card card, boolean animate) {
        if (card.isDismissible()) {
            card.getConfig().deleteObserver(this);
            if (animate) {
                mAnimation.animate(getPosition(card));
            } else {
                mCardList.remove(card);
                notifyDataSetChanged();
            }
        }
    }

    public void clearAll() {
        while(!mCardList.isEmpty()) {
            final Card card = mCardList.get(index);
            card.setDismissable(true);
            remove(card , false);
        }
    }

    public void clear() {
        for (int index = 0; index < mCardList.size();) {
            final Card card = mCardList.get(index);
            if(!card.isDismissable()) {
                index++;
            }
            remove(card, false);
        }
    }
```

**Comment by dexafree** [comment]
Working :+1: 

https://github.com/dexafree/MaterialList/commit/0637e11da6a6c113b1008813577bf650598bc859

Check it out and you'll say if we can consider this as fixed.

Thanks!

**Comment by FHellmann** [comment]
It also work's for me :+1:
